name: MLFlow and DVC Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./Question2 

      # Pull the latest dataset version from DVC remote
      - name: Pull latest dataset from DVC
        run: |
          dvc pull data/iris_dataset.csv.dvc  # Pull dataset from DVC remote storage
        working-directory: ./Question2

      # Train the model using the Python script
      - name: Train Model and Log Metrics, Parameters & Models
        run: |
          python src/train-local-filesystem.py
        working-directory: ./Question2

      # Track and commit dataset version with DVC
      - name: Track new dataset version with DVC
        run: |
          dvc add data/iris_dataset.csv  
          git add data/iris_dataset.csv.dvc  
          git commit -m "Update dataset version with DVC"  
        working-directory: ./Question2

      # Push the dataset to DVC remote storage
      - name: Push dataset to DVC remote
        run: |
          dvc push 
        working-directory: ./Question2

      # Push model and other changes to Git repository
      - name: Push model and other changes to Git
        run: |
          git add .  
          git commit -m "Update model and dataset version" 
          git push  
