name: MLFlow and DVC Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install dvc
        pip install mlflow

    # Pull dataset from DVC remote storage
    - name: DVC pull dataset
      run: |
        dvc pull data/iris_dataset.csv.dvc

    # Run the model training and tracking with MLFlow
    - name: Train model and track performance with MLflow
      run: |
        python train_model.py

    # Add model and dataset changes to DVC and commit
    - name: Track model and dataset with DVC
      run: |
        # Add model and dataset to DVC
        dvc add data/iris_dataset.csv
        dvc add models/logistic_regression_model.pkl
        
        # Commit changes
        git add .
        git commit -m "Update dataset and model"
        git push

  # Optionally, deploy to production or any other environment
  deploy:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy model
        run: |
          echo "Deploy model to production environment"
